### PR TITLE
Update to 20.08

### PR DESCRIPTION
**Pull request by Pobega**
I couldn't create `branch/20.08` but this will need to be merged into that rather than `branch/19.08`

### CODE REVIEW

**Comment by Pobega** [comment]
```/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: x86_64/.libs/Linit.o:/run/build/libunwind/src/x86_64/Ginit.c:52: multiple definition of `_U_dyn_info_list'; mi/.libs/dyn-info-list.o:/run/build/libunwind/src/mi/dyn-info-list.c:28: first defined here```

Looks like this was fixed in https://github.com/libunwind/libunwind/pull/166

**Comment by Pobega** [comment]
Looking at https://download.savannah.nongnu.org/releases/libunwind/ there doesn't seem to be a stable release that has this patch, so I'm going to try a pass with `-fcommon` as a build option (gcc 10 changed the default from to `-fno-common` which is what is causing this build failure)

**Comment by Yamgirly** [comment]
Are we going to see any movement on this? The latest version of the rider flatpak is based off 20.08, so this is relatively important to finish quickly

**Comment by refi64** [comment]
Merged by hand and [has been published](https://flathub.org/builds/#/builders/29/builds/19457).

**Pull request closed without merging**
